ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD . /app

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /app
RUN uv sync --locked

CMD ["uv", "run", "fastapi", "run", "main.py", "--port", "8000"]
